language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem install bundler
script: "script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false

cache: bundler
sudo: false
